var json={
	touImg:{
		touImg1:"img/tou1.jpg",
		touImg2:"img/tou2.jpg",
		touImg3:"img/tou3.jpg",
		touImg4:"img/tou4.jpg",
		touImg5:"img/tou5.jpg",
		touImg6:"img/tou6.jpg"
	},
	name:{
		name1:'张三',
		name2:'李四',
		name3:'王二',
		name4:'麻子',
		name5:'打手',
		name6:'审判官',
	},
	content:{
		con1:'希望有个人跟我一起像这对老夫妻一样相伴到老',
		con2:'我很看好你哦~~~来舞台上一起嗨吧',
		con3:'点击会有惊喜！！！',
		con4:'每当我心情不好的时候就会来这，安静的坐着看看来来往往的人和车',
		con5:'自己选择的路，在艰难，跪着也要走下去...',
		con6:'请记住我叫叶良辰！机智脸~~~'
	},
	photo:{
		photo1:"img/shipin1.jpg",
		photo2:"img/shipin2.jpg",
		photo3:"img/shipin3.jpg",
		photo4:"img/shipin4.jpg",
		photo5:"img/shipin5.jpg",
		photo6:"img/shipin6.jpg"
	}
}
console.log(json);
