var json={
	indexLi:[{
		touImg:"img/tou1.jpg",
		'nick':'倾雪怡然',
		content:'希望有个人跟我一起像这对老夫妻一样相伴到老',
		photo:"img/shipin1.jpg"
	},{
		touImg:"img/tou2.jpg",
		'nick':'执笔画卿颜',
		content:'我很看好你哦~~~来舞台上一起嗨吧',
		photo:"img/shipin2.jpg"
	},{
		touImg:"img/tou3.jpg",
		'nick':'這嗰丫頭、吥太乖°',
		content:'点击会有惊喜！！！',
		photo:"img/shipin3.jpg"
	},{
		touImg:"img/tou4.jpg",
		'nick':'夏沫青城',
		content:'每当我心情不好的时候就会来这，安静的坐着看看来来往往的人和车',
		photo:"img/shipin4.jpg"
	},{
		touImg:"img/tou5.jpg",
		'nick':'﹏北岛。',
		content:'自己选择的路，在艰难，跪着也要走下去...',
		photo:"img/shipin5.jpg"
	},{
		touImg:"img/tou6.jpg",
		'nick':'浅沫☆漓殇〃',
		content:'请记住我叫叶良辰！机智脸~~~',
		photo:"img/shipin.jpg"
	}]
}
