var json={
	indexLi1:[{
		touImg:"img/tou1.jpg",
		'nick':'倾雪怡然',
		content:'人人都忙于自己的欢喜与悲伤，哪有空顾你的孤独',
		photo:"img/shipin1.jpg"
	},{
		touImg:"img/tou2.jpg",
		'nick':'执笔画卿颜',
		content:'有很多人，慢慢地就散了，有很多事，渐渐地就淡了。有些路段，只能你一个人寂静地走；有些辛酸，只有我一个人无奈地尝。人生苦短，但愿有人，给我一世纵容。',
		photo:"img/shipin2.jpg"
	},{
		touImg:"img/tou3.jpg",
		'nick':'這嗰丫頭',
		content:'回忆不长，却让我喜欢上了你。余生不短，却不够我将你忘记。我已吹惯大风喝惯烈酒，你能不能对我说一句不要走。',
		photo:"img/shipin3.jpg"
	},{
		touImg:"img/tou4.jpg",
		'nick':'夏沫青城',
		content:'孤独的人最擅长假装自己很忙。',
		photo:"img/shipin4.jpg"
	},{
		touImg:"img/tou5.jpg",
		'nick':'北岛',
		content:'男人有了烟，有了啤酒，也就有了故事;女人有了钱，有了姿色，也就有了悲剧。',
		photo:"img/shipin5.jpg"
	},{
		touImg:"img/tou6.jpg",
		'nick':'浅沫漓殇',
		content:'别人怎么看你， 和你毫无关系 你要怎么活 ，也和别人毫无关系。',
		photo:"img/shipin6.jpg"
	}],
	indexLi2:[{
		touImg:"img/tou4.jpg",
		'nick':'叫我饭桶！',
		content:'希望有个人跟我一起像这对老夫妻一样相伴到老',
		photo:"img/shipin1.jpg"
	},{
		touImg:"img/tou6.jpg",
		'nick':'橙七の',
		content:'我很看好你哦~~~来舞台上一起嗨吧',
		photo:"img/shipin2.jpg"
	},{
		touImg:"img/tou1.jpg",
		'nick':'＿髷調﹫',
		content:'点击会有惊喜！！！',
		photo:"img/shipin3.jpg"
	},{
		touImg:"img/tou5.jpg",
		'nick':'τ wei ヾ',
		content:'每当我心情不好的时候就会来这，安静的坐着看看来来往往的人和车',
		photo:"img/shipin4.jpg"
	},{
		touImg:"img/tou2.jpg",
		'nick':'吢碎、囙憶那',
		content:'自己选择的路，在艰难，跪着也要走下去...',
		photo:"img/shipin5.jpg"
	},{
		touImg:"img/tou3.jpg",
		'nick':'Promise丶陌影',
		content:'请记住我叫叶良辰！机智脸~~~',
		photo:"img/shipin6.jpg"
	}]
}
